import { Providers } from "./provider";
import { ReactNode } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./componants/navbar/navbar";
import Form from "./form/page";
import Table from "./users/page";
import Map from "./componants/map";
import TextEditor from "./componants/texteditor/texteditor";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-black`}>
        <Providers>
          <Navbar />
          <div className="part1 mb-24 mt-[5%]  container m-auto">
            <div className="header p-2 md:p-0">
              <div className="flex items-center gap-2">
                <span className="block w-10 h-1 bg-violet-900 rounded mt-1"></span>
                <span className="text-[30px] font-bold">part 1</span>
              </div>
              <p className="text-sm md:w-3/4 mt-5 mb-10 text-neutral-500">Utilize the provided Strapi Api from the assessment to post user data into your redux store you are required to add one user into users collection and display this data un a table using a get request ensure the implementation of redux for state managment including both post request for adding a user and get requests for displaying the data in the table</p>
            </div>
            <div className="flex flex-col md:flex-row gap-10">
              <Form/>
              <Table/>
            </div>
          </div>
          <div className="part2 mb-24 mt-[5%]">
            <div className="header  p-2 md:p-0 container m-auto">
              <div className="flex items-center gap-2">
                <span className="block w-10 h-1 bg-violet-900 rounded mt-1"></span>
                <span className="text-[30px] font-bold">part 2</span>
              </div>
              <p className="text-sm md:w-3/4 mt-5 mb-10 text-neutral-500">implement a map using any library of your choice (leafflet is recommended).Search for coordinates of digifly company on google maps then place a tooltip at these coordinates ensure the tooltip styling matches the provided design below</p>
            </div>
            <div className="">
             <Map/>
            </div>
          </div>
          <div className="part3 mb-24 mt-[5%]  container m-auto">
          <div className="header p-2 md:p-0">
          <div className="flex items-center gap-2">
                <span className="block w-10 h-1 bg-violet-900 rounded mt-1"></span>
                <span className="text-[30px] font-bold">part 3</span>
              </div>
              <p className="text-sm md:w-3/4 mt-5 mb-10 text-neutral-500">implement a text editor that precisely replicates the UI styles provided. it's essential to create the undo and redo function from scratch,alon with two additional features of your choice you mau use any package but creating these functionalities from scratch will be advantage ensure that all text editor functions are operational</p>
            </div>
            <div className="w-full">
             <TextEditor/>
            </div>
          </div>
      
        </Providers>
        <footer className="bg-violet-900 text-white p-4 w-full relative text-center">
            all copyright reserved
          </footer>
      </body>
    </html>
  );
}

export default RootLayout;
